# Generated by Django 5.0 on 2024-01-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='account/media/uploads/'),
        ),
    ]
