# Generated by Django 5.0 on 2024-01-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt_1', models.CharField(max_length=250)),
                ('opt_2', models.CharField(max_length=250)),
                ('opt_3', models.CharField(max_length=250)),
                ('opt_4', models.CharField(max_length=250)),
                ('time_limit', models.IntegerField()),
                ('right_opt', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
