# Generated by Django 5.0 on 2024-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempts',
            name='last_question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
