# Generated by Django 5.0 on 2024-01-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_userquizattempts_last_question_id_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizattempts',
            name='last_question_id',
        ),
    ]
